---
name: Github Action

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  self:
    name: lint actions config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # https://github.com/karancode/yamllint-github-action
      - name: yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .github/workflows/*.yml
          yamllint_config_filepath: .yamllint
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labkey-lint: &lint-template
    name: labkey-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/luizm/action-sh-checker
      - &step-sh-checker
        name: shfmt & shellcheck
        uses: luizm/action-sh-checker@v0.3.0
        with:
          sh_checker_exclude: test/shunit2 install-wcp.bash
          sh_checker_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s -i 2
          SHELLCHECK_OPTS: -x install-labkey.bash -x test/helpers.sh

  labkey-test: &test-template
    name: labkey-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - &step-shunit
        name: shunit2
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: test/runner.sh labkey

  wcp-lint:
    <<: *lint-template
    name: wcp-lint
    steps:
      - uses: actions/checkout@v2

      - <<: *step-sh-checker
        with:
          sh_checker_exclude: test/shunit2 install-install.bash
          sh_checker_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s -i 2
          SHELLCHECK_OPTS: -x install-wcp.bash -x test/helpers.sh

  wcp-test:
    <<: *test-template
    name: wcp-test
    steps:
      - uses: actions/checkout@v2

      - <<: *step-shunit
        with:
          cli: test/runner.sh wcp
