---
name: Github Action

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/luizm/action-sh-checker
      - name: sh-checker
        uses: luizm/action-sh-checker@v0.3.0
        with:
          sh_checker_exclude: test/shunit2
          sh_checker_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -s -i 2

      # https://github.com/karancode/yamllint-github-action
      - name: yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .github/workflows/*.yml
          yamllint_config_filepath: .yamllint
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shunit2
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "test/runner.sh"
